USE [master]
GO
/****** Object:  Database [uber]    Script Date: 05/05/2023 19:38:22 ******/
CREATE DATABASE [uber]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'uber', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\uber.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'uber_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\uber_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [uber] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [uber].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [uber] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [uber] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [uber] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [uber] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [uber] SET ARITHABORT OFF 
GO
ALTER DATABASE [uber] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [uber] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [uber] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [uber] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [uber] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [uber] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [uber] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [uber] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [uber] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [uber] SET  ENABLE_BROKER 
GO
ALTER DATABASE [uber] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [uber] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [uber] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [uber] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [uber] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [uber] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [uber] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [uber] SET RECOVERY FULL 
GO
ALTER DATABASE [uber] SET  MULTI_USER 
GO
ALTER DATABASE [uber] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [uber] SET DB_CHAINING OFF 
GO
ALTER DATABASE [uber] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [uber] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [uber] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [uber] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'uber', N'ON'
GO
ALTER DATABASE [uber] SET QUERY_STORE = OFF
GO
USE [uber]
GO
/****** Object:  Table [dbo].[Motorista]    Script Date: 05/05/2023 19:38:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Motorista](
	[CNH] [int] NOT NULL,
	[nome] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[CNH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 05/05/2023 19:38:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[placa] [varchar](8) NOT NULL,
	[CNH] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[placa] ASC,
	[CNH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Veiculo]    Script Date: 05/05/2023 19:38:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Veiculo](
	[placa] [varchar](8) NOT NULL,
	[modelo] [varchar](40) NOT NULL,
	[ano] [int] NULL,
	[preco] [decimal](10, 2) NULL,
	[dataCompra] [smalldatetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[placa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Motorista] ([CNH], [nome]) VALUES (842342, N'Genne Smon')
GO
INSERT [dbo].[Motorista] ([CNH], [nome]) VALUES (8748398, N'Elen dos Santos')
GO
INSERT [dbo].[Motorista] ([CNH], [nome]) VALUES (9458321, N'Pauley Stanley')
GO
INSERT [dbo].[Motorista] ([CNH], [nome]) VALUES (9840232, N'Rose klent')
GO
INSERT [dbo].[Veiculo] ([placa], [modelo], [ano], [preco], [dataCompra]) VALUES (N'PER-2399', N'Honda Civic', 2020, CAST(104000.00 AS Decimal(10, 2)), CAST(N'2023-01-02T00:00:00' AS SmallDateTime))
GO
ALTER TABLE [dbo].[Permissao]  WITH CHECK ADD  CONSTRAINT [FK_Permissao_Motorista] FOREIGN KEY([CNH])
REFERENCES [dbo].[Motorista] ([CNH])
GO
ALTER TABLE [dbo].[Permissao] CHECK CONSTRAINT [FK_Permissao_Motorista]
GO
ALTER TABLE [dbo].[Permissao]  WITH CHECK ADD  CONSTRAINT [FK_Permissao_Veiculo] FOREIGN KEY([placa])
REFERENCES [dbo].[Veiculo] ([placa])
GO
ALTER TABLE [dbo].[Permissao] CHECK CONSTRAINT [FK_Permissao_Veiculo]
GO
USE [master]
GO
ALTER DATABASE [uber] SET  READ_WRITE 
GO
