USE MASTER
GO

USE pedidos
GO

--CRIAÇÃO DE TRIGGER PARA EXERCICIO, (ESTUDANDO PARA PROVA)
CREATE OR ALTER TRIGGER TRG_ITEM_PEDIDO_INSERT ON EX2_ITEMPEDIDO
after INSERT AS
BEGIN
	--DECLARAÇÃO DE VARIAVEIS
	DECLARE @CODPEDIDO INT,
			@QTDPRODUTO INT,
			@CODPRODUTO INT,
			@QTDNEWINSERT INT;
	
	--OBTEM OS DADOS INSERIDOS
	SELECT @CODPEDIDO = codpedido, @QTDPRODUTO = quantidade, @CODPRODUTO = codproduto FROM inserted;
	
	--VERIFICAÇÃO PARA VER SE O CÓDIGO DO PEDIDO JÁ EXISTE NA TABELA 'EX2_PEDIDO'
	IF NOT EXISTS (SELECT 1
					FROM EX2_PEDIDO
					WHERE codpedido = @CODPEDIDO) 
	BEGIN
		raiserror(N'O código do pedido não existe na tabela de Pedido.', 16, 0);
		ROLLBACK transaction;
	END
	ELSE
	BEGIN
		PRINT 'Dados includos com sucesso';
	END
	
	--VERIFICA SE A QUANTIDADE DE PRODUTOS INSERIDOS É MAIOR DO QUE A QUANTIDADE EM
	--ESTOQUE NA TABELA 'EX2_PRODUTO'
	IF(SELECT quantidade FROM EX2_PRODUTO WHERE codproduto = @CODPRODUTO) < @QTDPRODUTO
	BEGIN
		RAISERROR('A quantidade do pedido é maior que a quantidade em estoque!',16,1);
		ROLLBACK TRANSACTION;
	END

	--FAZER A ATUALIZAÇÃO DA QUANTIDADE EM ESTOQUE 
	--CASO SEJA MENOR QUE 5 GERAR UM REGISTRO DE PEDIDO DE 2,5X A QUANTIDADE DO ESTOQUE ATUAL
	--NA TABELA 'EX2_REQUISICAO_COMPRA'
	SELECT @QTDNEWINSERT = (SELECT * FROM EX2_PRODUTO WHERE codproduto = @CODPRODUTO)*2.5;

	IF(SELECT quantidade FROM EX2_PRODUTO WHERE codproduto = @CODPRODUTO) < 5
	BEGIN
		INSERT INTO EX2_REQUISICAO_COMPRA (codproduto,quantidade)
			VALUES (@CODPRODUTO,@QTDNEWINSERT);

		PRINT 'FOI INSERIDO UM REGISTRO DE REQUISIÇÃO DE COMPRA!';
	END

END

SELECT * FROM EX2_ITEMPEDIDO

SELECT * FROM EX2_PEDIDO

SELECT * FROM EX2_PRODUTO

SELECT * FROM EX2_REQUISICAO_COMPRA

--inserindo valor na tabela de itempedidos
insert into EX2_ITEMPEDIDO (codpedido,numeroitem,valorunitario,quantidade,codproduto)
	values(2, 3, CAST(20.90 AS Decimal(10, 2)), 14, 1)

DELETE FROM EX2_ITEMPEDIDO WHERE codpedido = 2 AND numeroitem = 3

SELECT quantidade FROM EX2_PRODUTO WHERE codproduto = 1